=== 15831944/virtuoso/binsrc/samples/schemaview/xmlsource/test0001/choice-bug1.xsd
<!--
 -  
 -  This file is part of the OpenLink Software Virtuoso Open-Source (VOS)
 -  project.
 -  
 -  Copyright (C) 1998-2006 OpenLink Software
 -  
 -  This project is free software; you can redistribute it and/or modify it
 -  under the terms of the GNU General Public License as published by the
 -  Free Software Foundation; only version 2 of the License, dated June 1991.
 -  
 -  This program is distributed in the hope that it will be useful, but
 -  WITHOUT ANY WARRANTY; without even the implied warranty of
 -  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 -  General Public License for more details.
 -  
 -  You should have received a copy of the GNU General Public License along
 -  with this program; if not, write to the Free Software Foundation, Inc.,
 -  51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 -  
 -  
-->
<?xml version="1.0"?>
<!DOCTYPE xs:schema SYSTEM "XMLSchema.dtd">
<xs:schema>

<xs:element name="testb">
 <xs:complexType>
  <xs:sequence>
   <xs:element ref="sub0" minOccurs="0"/>
   <xs:element ref="sub3" minOccurs="0"/>
   <xs:choice minOccurs="0" maxOccurs="1">
    <xs:element ref="sub1"/>
    <xs:element ref="sub2"/>
    <xs:group ref="appendix.class"/>
   </xs:choice>
  </xs:sequence>
 </xs:complexType>
</xs:element>

<xs:group name="appendix.class">
 <xs:choice>
  <xs:element ref="appendix"/>
 </xs:choice>
</xs:group>

<xs:element name="main">
  <xs:complexType>
    <xs:sequence>
	<xs:element ref="testb" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="sub0" type="xs:string"/>
<xs:element name="sub1" type="xs:string"/>
<xs:element name="sub2" type="xs:string"/>
<xs:element name="sub3" type="xs:string"/>
<xs:element name="sub4" type="xs:string"/>
<xs:element name="appendix" type="xs:string"/>
</xs:schema>

=== 15831944/virtuoso/binsrc/samples/schemaview/xmlsource/test0001/choice-bug1.xml
<!--
 -  
 -  This file is part of the OpenLink Software Virtuoso Open-Source (VOS)
 -  project.
 -  
 -  Copyright (C) 1998-2006 OpenLink Software
 -  
 -  This project is free software; you can redistribute it and/or modify it
 -  under the terms of the GNU General Public License as published by the
 -  Free Software Foundation; only version 2 of the License, dated June 1991.
 -  
 -  This program is distributed in the hope that it will be useful, but
 -  WITHOUT ANY WARRANTY; without even the implied warranty of
 -  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 -  General Public License for more details.
 -  
 -  You should have received a copy of the GNU General Public License along
 -  with this program; if not, write to the Free Software Foundation, Inc.,
 -  51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 -  
 -  
-->
<main schemaLocation="choice-bug1.xsd">
 <testb>
  <sub0> hello </sub0>
  <sub1/>
 </testb>

 <testb>
  <sub0/>
  <sub2/>
 </testb>

 <testb>
  <sub0/>
  <appendix/>
 </testb>
</main>
