=== 15831944/virtuoso/binsrc/samples/schemaview/xmlsource/test0001/clean-003.xsd
<!--
 -  
 -  This file is part of the OpenLink Software Virtuoso Open-Source (VOS)
 -  project.
 -  
 -  Copyright (C) 1998-2006 OpenLink Software
 -  
 -  This project is free software; you can redistribute it and/or modify it
 -  under the terms of the GNU General Public License as published by the
 -  Free Software Foundation; only version 2 of the License, dated June 1991.
 -  
 -  This program is distributed in the hope that it will be useful, but
 -  WITHOUT ANY WARRANTY; without even the implied warranty of
 -  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 -  General Public License for more details.
 -  
 -  You should have received a copy of the GNU General Public License along
 -  with this program; if not, write to the Free Software Foundation, Inc.,
 -  51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 -  
 -  
-->
<?xml version="1.0"?>
<!DOCTYPE xs:schema SYSTEM "XMLSchema.dtd" [
 <!ENTITY % schemaAttrs "
        xmlns:r		CDATA	#IMPLIED
        xmlns:xipo	CDATA	#IMPLIED
 ">
]>	
<xs:schema targetNamespace="http://www.example.com/Report"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:r="http://www.example.com/Report"
        xmlns:xipo="http://www.example.com/IPO"
        elementFormDefault="qualified">

<xs:element name="person" type="r:aPerson"/>
	<xs:complexType name="aPerson">
		<xs:sequence>
			<xs:element ref="r:firstName" maxOccurs="2"/>
			<xs:element ref="r:lastName"/>
			<xs:choice>
				<xs:element ref="r:age"/>
				<xs:element ref="r:birthDate"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="status" type="string" use="optional"/>
		<xs:attribute name="chilrens" type="positiveInteger" use="optional"/>
		<xs:attributeGroup ref="r:citizenship"/>
	</xs:complexType>
<xs:attributeGroup name="citizenship">
	<xs:attribute name="country" type="string" use="optional"/>
	<xs:attribute name="cstatus" type="string" use="optional"/>
</xs:attributeGroup>


<xs:element name="manager">
 <xs:complexType>
  <xs:complexContent>
   <xs:extension base="r:aPerson">
	<xs:attribute name="employer" type="string" use="optional"/>
	<xs:attribute name="salary" type="positiveInteger" use="optional"/>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
</xs:element>

<xs:element name="report">
	<xs:complexType>
		<xs:sequence> 
			<xs:element ref="r:person" minOccurs="5" maxOccurs="5"/>
			<xs:element ref="r:manager" minOccurs="5" maxOccurs="5"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="firstName" type="string"/>
<xs:element name="lastName" type="string"/>
<xs:element name="age" type="positiveInteger"/>
<xs:element name="birthDate" type="date"/>

</xs:schema>

=== 15831944/virtuoso/binsrc/samples/schemaview/xmlsource/test0001/persons-003.xml
<!--
 -  
 -  This file is part of the OpenLink Software Virtuoso Open-Source (VOS)
 -  project.
 -  
 -  Copyright (C) 1998-2006 OpenLink Software
 -  
 -  This project is free software; you can redistribute it and/or modify it
 -  under the terms of the GNU General Public License as published by the
 -  Free Software Foundation; only version 2 of the License, dated June 1991.
 -  
 -  This program is distributed in the hope that it will be useful, but
 -  WITHOUT ANY WARRANTY; without even the implied warranty of
 -  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 -  General Public License for more details.
 -  
 -  You should have received a copy of the GNU General Public License along
 -  with this program; if not, write to the Free Software Foundation, Inc.,
 -  51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 -  
 -  
-->
<?xml version='1.0'?>
<r:report xmlns='http://www.oasis-open.org/docbook/schema/4.1.2'
	   xmlns:r='http://www.oasis-open.org/docbook/schema/4.1.2'
           xmlns:xsi='http://www.w3.org/2000/10/XMLSchema-instance'
           xmlns:tbl='http://www.oasis-open.org/tables/exchange/1.0'
	  schemaLocation='clean-003.xsd'>
<!--
	handling occurence restrictions 
-->
<r:person>
	<r:firstName> Ruslan </r:firstName>
	<r:lastName> Abdulkhalikov </r:lastName>
	<r:age value="23"/>
</r:person>
<r:person>
	<r:firstName> Ruslan </r:firstName>
	<r:lastName> Abdulkhalikov </r:lastName>
	<r:birthDate value="1978-02-14"/>
</r:person>
<r:person>
	<r:firstName> Ruslan </r:firstName>
	<r:lastName> Abdulkhalikov </r:lastName>
	<r:birthDate value="1978-02-14"/>
</r:person>
<r:person>
	<r:firstName> Ruslan </r:firstName>
	<r:lastName> Abdulkhalikov </r:lastName>
	<r:birthDate value="1978-02-14"/>
</r:person>
<r:person>
	<r:firstName> Ruslan </r:firstName>
	<r:lastName> Abdulkhalikov </r:lastName>
	<r:birthDate value="1978-02-14"/>
</r:person>
<r:manager employer="Openlink">
	<r:firstName> Ruslan </r:firstName>
	<r:lastName> Abdulkhalikov </r:lastName>
	<r:age value="23"/>
</r:manager>
<r:manager>
	<r:firstName> Ruslan </r:firstName>
	<r:lastName> Abdulkhalikov </r:lastName>
	<r:age value="23"/>
</r:manager> 
<r:manager>
	<r:firstName> Ruslan </r:firstName>
	<r:lastName> Abdulkhalikov </r:lastName>
	<r:age value="23"/>
</r:manager> 

</r:report>
